### ISSUE TITLE
那不是接口层也有引入dubbo3？

### ISSUE THREAD

**Issue by shenzhuan** [linux-china/spring-boot-dubbo#7]
@DubboConsumer
   private UicTemplate uicTemplate;

**Comment by shenzhuan** [comment]
错了  是找不到 @DubboConsumer  这个类，是不是还要引用
https://github.com/alibaba/spring-boot-starter-dubbo  这个包才可以，我还以为你的start已经包含了他的

**Comment by linux-china** [comment]
com.alibaba.dubbo.config.annotation.DubboConsumer  这个在Dubbo3的代码中，你需要自行编译。
