### ISSUE TITLE
spring-boot-starter-dubbo maven仓库找不到该jar

### ISSUE THREAD

**Issue by 205140040** [linux-china/spring-boot-dubbo#8]
spring-boot-starter-dubbo maven仓库找不到该jar

**Comment by linux-china** [comment]
这个没有发布到maven中心仓库，需要自行编译，发布到内部maven仓库中。由于alibaba拥有dubbo的groupId，如果发布到maven中仓库会混乱。 同时spring-boot-starter-dubbo需要dubbo3版本，也难做到一些。

**Comment by 205140040** [comment]
奥

**Comment by shenkaibo** [comment]
找不到 com.alibaba.dubbo.3.0.0-SNAPSHOT 的包
